FROM public.ecr.aws/clique/clique-sibyl-dcsv2-base:2.1.2 AS BUILDER
COPY . $APP_DIR/SibylDataConnectors
RUN bash -c "$BUILD_SCRIPT"
RUN rm -rf $APP_DIR/SibylDataConnectors


FROM public.ecr.aws/clique/clique-sibyl-dcsv2-base:2.1.2
COPY --from=BUILDER $APP_DIR $APP_DIR